{
  "openapi": "3.0.0",
  "info": {
    "title": "Postech - Fase 2 - Fastfood",
    "version": "1.0.0",
    "description": "API com Clean Architecture"
  },
  "paths": {
    "/clients": {
      "post": {
        "summary": "Cria um novo cliente",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "cpf": {
                    "type": "string"
                  }
                },
                "required": ["nome", "email", "cpf"]
              },
              "examples": {
                "example1": {
                  "summary": "Exemplo de criação de Cliente 1",
                  "value": {
                    "nome": "John Doe",
                    "email": "john.doe@example.com",
                    "cpf": "12345678912"
                  }
                },
                "example2": {
                  "summary": "Exemplo de erro na criação",
                  "value": {
                    "none": "Jane Doe"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Cliente criado com sucesso",
            "content": {
              "application/json": {
                "examples": {
                  "success": {
                    "summary": "Cliente criado com sucesso",
                    "value": {
                      "cpf": "12345678912",
                      "nome": "John Doe",
                      "email": "john.doe@example.com"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno de servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "errorExample": {
                    "summary": "Exemplo de resposta de erro",
                    "value": {
                      "error": "Error creating client: Missing required fields"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products": {
      "post": {
        "summary": "Cria um novo produto",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "price": {
                    "type": "string"
                  },
                  "category": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  }
                },
                "required": ["name", "price", "category", "description"]
              },
              "examples": {
                "example1": {
                  "summary": "Exemplo de criação de Produto 1",
                  "value": {
                    "name": "Produto Exemplo",
                    "price": "19.99",
                    "category": "Lanche",
                    "description": "Descrição do produto exemplo"
                  }
                },
                "example2": {
                  "summary": "Exemplo de erro na criação",
                  "value": {
                    "name": "Produto Sem Preço"
                  }
                },
                "example3": {
                  "summary": "Exemplo de erro de categoria",
                  "value": {
                    "name": "Produto Exemplo",
                    "price": "19.99",
                    "category": "LANCHE",
                    "description": "Descrição do produto exemplo"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Produto criado com sucesso",
            "content": {
              "application/json": {
                "examples": {
                  "success": {
                    "summary": "Produto criado com sucesso",
                    "value": {
                      "id": "123456",
                      "name": "Produto Exemplo",
                      "price": "19.99",
                      "category": "Lanche",
                      "description": "Descrição do produto exemplo",
                      "createdAt": "2023-10-01T12:00:00Z",
                      "updatedAt": "2023-10-01T12:00:00Z"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno de servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "errorExample": {
                    "summary": "Exemplo de resposta de erro",
                    "value": {
                      "error": "Error creating product: Missing required fields"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/combo": {
      "get": {
        "summary": "Lista produtos para o combo",
        "description": "Retorna uma lista de produtos das categorias 'Lanche', 'Acompanhamento' e 'Bebida' ordenados por nome.",
        "responses": {
          "200": {
            "description": "Lista de produtos para combo",
            "content": {
              "application/json": {
                "examples": {
                  "success": {
                    "summary": "Exemplo de resposta bem-sucedida",
                    "value": {
                      "Lanche": [
                        {
                          "_id": "66a8d2cc53aba32975a666cd",
                          "name": "Hamburguer",
                          "price": "10.00",
                          "category": "Lanche",
                          "description": "Delicioso hamburguer",
                          "createdAt": "2023-10-01T12:00:00Z",
                          "updatedAt": "2023-10-01T12:00:00Z"
                        }
                      ],
                      "Acompanhamento": [
                        {
                          "_id": "66a8d2cc53aba32975a666c2",
                          "name": "Batata Frita",
                          "price": "5.00",
                          "category": "Acompanhamento",
                          "description": "Batata frita crocante",
                          "createdAt": "2023-10-01T12:00:00Z",
                          "updatedAt": "2023-10-01T12:00:00Z"
                        }
                      ],
                      "Bebida": [
                        {
                          "_id": "66a8d2cc53aba32975a666c3",
                          "name": "Refrigerante",
                          "price": "3.00",
                          "category": "Bebida",
                          "description": "Refrigerante gelado",
                          "createdAt": "2023-10-01T12:00:00Z",
                          "updatedAt": "2023-10-01T12:00:00Z"
                        }
                      ]
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno de servidor",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "errorExample": {
                    "summary": "Exemplo de resposta de erro",
                    "value": {
                      "error": "Erro ao buscar produtos"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Client": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "nome": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "Product": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "enum": ["Lanche", "Acompanhamento", "Bebida", "Sobremesa"]
          },
          "description": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}
